version: '3.8'

x-common-variables: &common-variables
  API_KEY: docker-compose-key

services:
  frontend:
    container_name: ecfr-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.local
      target: runner
    restart: always
    volumes:
      - ./apps/frontend/src:/opt/apps/frontend/src
      - ./apps/frontend/package.json:/opt/apps/frontend/package.json
    environment:
      NEXT_PUBLIC_BACK_END_API_URL: http://localhost:4535
      NEXT_PUBLIC_APP_API_KEY: docker-compose-key
    ports:
      - 3000:3000
    networks:
      - ecfr

  backend:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.local
      target: development
    working_dir: /opt
    container_name: ecfr-backend
    environment:
      <<: *common-variables
    volumes:
      - ./apps/api/src:/opt/apps/api/src
      - ./apps/api/package.json:/opt/apps/api/package.json
    ports:
      - 4535:4535
    networks:
      - ecfr

networks:
  ecfr:
    name: ecfr
