version: '1'

services:
  - type: web
    name: frontend-ecfr
    runtime: docker
    plan: starter
    previewPlan: starter
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    dockerContext: .
    dockerfilePath: apps/frontend/Dockerfile.render
    buildFilter:
      paths:
        - apps/frontend/**
        - turbo.json

  - type: pserv
    name: backend-ecfr
    runtime: docker
    plan: standard
    previewPlan: starter
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    dockerContext: .
    dockerfilePath: apps/api/Dockerfile.render
    buildFilter:
      paths:
        - apps/api/**
        - turbo.json
