version: '1'

previewsEnabled: true
previewsExpireAfterDays: 1
databases:
  - name: ecfr-db
    databaseName: ecfr
    user: admin
    plan: basic-1gb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: '16'

services:
  - type: web
    name: frontend-ecfr
    runtime: docker
    plan: starter
    previewPlan: starter
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    dockerContext: .
    dockerfilePath: apps/frontend/Dockerfile.render
    buildFilter:
      paths:
        - apps/frontend/**
        - turbo.json

  - type: pserv
    name: backend-ecfr
    runtime: docker
    plan: standard
    previewPlan: starter
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: ecfr-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: ecfr-db
          property: database
      - key: DB_ADMIN_USER
        fromDatabase:
          name: ecfr-db
          property: user
      - key: DB_ADMIN_PASSWORD
        fromDatabase:
          name: ecfr-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: ecfr-db
          property: port
      - key: DB_APP_USER
        value: ecfr
      - key: DB_APP_PASSWORD
        generateValue: true
    region: oregon
    dockerContext: .
    dockerfilePath: apps/api/Dockerfile.render
    buildFilter:
      paths:
        - apps/api/**
        - turbo.json
