export const AMBIGUOUS_TERMS = new Set([
  // Vague qualifiers
  'reasonable',
  'appropriate',
  'substantial',
  'generally',
  'normally',
  'usually',
  'typically',
  'relatively',
  'fairly',
  'quite',
  'rather',
  'somewhat',
  'significant',
  'adequate',
  'sufficient',

  // Uncertain time references
  'soon',
  'promptly',
  'timely',
  'periodic',
  'regular',
  'frequent',
  'occasional',

  // Undefined quantities
  'many',
  'few',
  'several',
  'various',
  'numerous',
  'some',
  'any',
  'certain',

  // Unclear requirements
  'should',
  'may',
  'might',
  'could',
  'would',
  'can',

  // Vague conditions
  'etc',
  'and so forth',
  'and/or',
  'as applicable',
  'as appropriate',
  'as necessary',

  // Subjective terms
  'good',
  'bad',
  'better',
  'worse',
  'best',
  'worst',
  'adequate',
  'satisfactory',

  // Undefined scope
  'including',
  'such as',
  'related to',
  'associated with',
  'relevant',
  'applicable',

  // Unclear exceptions
  'unless',
  'except',
  'other than',
  'notwithstanding',

  // Undefined standards
  'normal',
  'standard',
  'typical',
  'common',
  'ordinary',
  'regular',
  'conventional',
])

export const TECHNICAL_TERMS = new Set([
  'pursuant',
  'hereunder',
  'thereof',
  'whereof',
  'herein',
  'aforementioned',
  'notwithstanding',
  'whereby',
  'hereinafter',
  'foregoing',
  'thereby',
  'therein',
  'wherein',
  'hereby',
  'stipulated',
  'promulgated',
  'subsequent',
  'precedent',
  'jurisdiction',
  'statutory',
  'regulatory',
  'compliance',
  'provision',
  'subsection',
  'amendment',
  'authorization',
  'prerequisite',
  'exemption',
  'violation',

  // Additional legal/technical terms
  'adjudicate',
  'affidavit',
  'allegation',
  'appellant',
  'arbitration',
  'breach',
  'covenant',
  'decree',
  'deposition',
  'enjoin',
  'estoppel',
  'execution',
  'forthwith',
  'grievance',
  'indemnify',
  'injunction',
  'litigation',
  'mandate',
  'negligence',
  'pleading',
  'proximate',
  'recusal',
  'remedy',
  'rescind',
  'sanction',
  'statute',
  'subpoena',
  'tort',
  'warrant',

  // Regulatory/Administrative terms
  'administrative',
  'agency',
  'applicability',
  'certification',
  'delegation',
  'designation',
  'disclosure',
  'enforcement',
  'implementation',
  'notification',
  'procurement',
  'protocol',
  'regulation',
  'requirement',
  'specification',
  'submission',
  'verification',

  // Technical process terms
  'accordance',
  'amended',
  'annotation',
  'appendix',
  'citation',
  'codification',
  'compilation',
  'pursuant',
  'reference',
  'revision',

  // Document structure terms
  'clause',
  'paragraph',
  'provision',
  'section',
  'subsection',
  'subtitle',
  'subpart',
  'title',

  // Action terms
  'abolish',
  'accommodate',
  'administer',
  'authorize',
  'constitute',
  'designate',
  'establish',
  'execute',
  'implement',
  'prescribe',
  'prohibit',
  'terminate',

  // Qualifying terms
  'applicable',
  'appropriate',
  'designated',
  'eligible',
  'mandatory',
  'permissible',
  'prescribed',
  'prohibited',
  'respective',
  'specified',

  // Time-related terms
  'forthwith',
  'henceforth',
  'heretofore',
  'immediate',
  'pending',
  'subsequent',
  'termination',

  // Process-related terms
  'procedure',
  'process',
  'protocol',
  'provision',
  'requirement',
  'standard',
  'guideline',
  'methodology',
])

export const RESTRICTION_WORDS = new Set([
  'shall',
  'must',
  'required',
  'prohibited',
  'mandatory',
  'requires',
  'obligation',
  'obligations',
  'requirement',
  'requirements',
  'forbidden',
  'prohibited',
  'restrict',
  'restricted',
  'restriction',
  'limitations',
  'limited to',
  'only if',
  'subject to',
  'conditional',
])

export const EXCEPTION_WORDS = new Set([
  'except',
  'unless',
  'waiver',
  'exemption',
  'notwithstanding',
  'excluding',
  'excluded',
  'exempted',
  'waived',
  'provided that',
  'subject to exception',
  'may be waived',
  'discretion',
  'alternative',
  'variance',
  'deviation',
  'special cases',
  'extraordinary circumstances',
])

export const COMPLIANCE_PATTERNS = {
  reporting: [
    /submit.*report/i,
    /reporting requirement/i,
    /shall report/i,
    /must notify/i,
    /submission of data/i,
  ],
  recordKeeping: [
    /maintain.*records/i,
    /recordkeeping/i,
    /documentation required/i,
    /shall retain/i,
    /must keep/i,
  ],
  testing: [
    /test.*required/i,
    /testing procedure/i,
    /shall be tested/i,
    /measurement required/i,
    /monitoring requirement/i,
  ],
  certification: [
    /certification required/i,
    /shall certify/i,
    /must be certified/i,
    /certification process/i,
  ],
  financial: [
    /financial.*requirement/i,
    /payment of fee/i,
    /cost of compliance/i,
    /financial responsibility/i,
  ],
}

export const ENFORCEMENT_PATTERNS = {
  penalties: [/civil penalty/i, /criminal penalty/i, /fine/i, /enforcement action/i, /liable for/i],
  inspections: [
    /inspection required/i,
    /shall inspect/i,
    /subject to inspection/i,
    /examination of/i,
  ],
  audits: [/audit requirement/i, /shall be audited/i, /compliance audit/i, /review process/i],
}

export const countPatternMatches = (text: string, patterns: RegExp[]): number =>
  patterns.reduce((count, pattern) => count + (text.match(pattern)?.length || 0), 0)
